export enum AuthRepositoryEnum {
  AUDIT_REPOSITORY = 'AUDIT_REPOSITORY',
  MENU_REPOSITORY = 'MENU_REPOSITORY',
  PERMISSION_REPOSITORY = 'PERMISSION_REPOSITORY',
  ROLE_REPOSITORY = 'ROLE_REPOSITORY',
  TRANSACTIONAL_CODE_REPOSITORY = 'TRANSACTIONAL_CODE_REPOSITORY',
  USER_REPOSITORY = 'USER_REPOSITORY',
  ADDRESS_REPOSITORY = 'ADDRESS_REPOSITORY',
  ADDITIONAL_INFORMATION_REPOSITORY = 'ADDITIONAL_INFORMATION_REPOSITORY',
}

export enum CommonRepositoryEnum {
  FILE_REPOSITORY = 'FILE_REPOSITORY',
  CATALOGUE_REPOSITORY = 'CATALOGUE_REPOSITORY',
  DPA_REPOSITORY = 'DPA_REPOSITORY',
}

export enum CoreRepositoryEnum {
  PARTICIPANT_REPOSITORY = 'PARTICIPANT_REPOSITORY',
}

export enum TeacherEvaluationRepositoryEnum {
  QUESTION_REPOSITORY = 'QUESTION_REPOSITORY',
  STUDENT_EVALUATION_REPOSITORY = 'STUDENT_EVALUATION_REPOSITORY',
  RESPONSE_REPOSITORY = 'RESPONSE_REPOSITORY',
  EVALUATION_REPOSITORY = 'EVALUATION_REPOSITORY',
  AUTO_EVALUATION_REPOSITORY = 'AUTO_EVALUATION_REPOSITORY',
  PARTNER_EVALUATION_REPOSITORY = 'PARTNER_EVALUATION_REPOSITORY',
  COORDINATOR_EVALUATION_REPOSITORY = 'COORDINATOR_EVALUATION_REPOSITORY',
  RESULT_REPOSITORY = 'RESULT_REPOSITORY',
}
